# Generated by Django 2.2.3 on 2019-07-03 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=16, verbose_name='账户')),
                ('user_password', models.CharField(max_length=32, verbose_name='密码')),
                ('identity', models.CharField(max_length=16, verbose_name='身份')),
            ],
        ),
        migrations.CreateModel(
            name='ClassroomInformation',
            fields=[
                ('classroom_id', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='教室号')),
                ('classroom_name', models.CharField(max_length=32, verbose_name='教室名')),
                ('classroom_number', models.IntegerField(verbose_name='容纳人数')),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentInformation',
            fields=[
                ('department_id', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='部门号')),
                ('department_name', models.CharField(max_length=32, verbose_name='部门名称')),
            ],
        ),
        migrations.CreateModel(
            name='MajorInformation',
            fields=[
                ('major_id', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='专业号')),
                ('major_name', models.CharField(max_length=32, verbose_name='专业名')),
            ],
        ),
        migrations.CreateModel(
            name='StudentInformation',
            fields=[
                ('sno', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='学号，主键')),
                ('sname', models.CharField(max_length=32, verbose_name='学生姓名')),
                ('ssex', models.IntegerField(verbose_name='学生性别')),
                ('birthdate', models.DateField(verbose_name='出生日期')),
                ('admission', models.DateField(verbose_name='入学时间')),
                ('major_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP01.MajorInformation', verbose_name='专业号')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherInformation',
            fields=[
                ('teacher_id', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='指导老师编号')),
                ('tname', models.CharField(max_length=32, verbose_name='老师姓名')),
                ('tsex', models.IntegerField(verbose_name='教师性别')),
                ('tage', models.IntegerField(verbose_name='教师年龄')),
                ('tsalaries', models.IntegerField(verbose_name='薪水')),
                ('entry_time', models.DateField(verbose_name='入职时间')),
                ('rank', models.CharField(max_length=16, verbose_name='职称')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectInformation',
            fields=[
                ('subject_id', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='课程号')),
                ('subject_name', models.CharField(max_length=32, verbose_name='课程名称')),
                ('start_time', models.DateField(verbose_name='开始时间')),
                ('end_time', models.DateField(verbose_name='结束时间')),
                ('classroom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP01.ClassroomInformation', verbose_name='教室号')),
            ],
        ),
        migrations.CreateModel(
            name='StudentSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times', models.IntegerField(default=3, verbose_name='考试次数')),
                ('score', models.IntegerField(verbose_name='分数')),
                ('student_id', models.ForeignKey(on_delete=models.Model, to='APP01.StudentInformation', verbose_name='学生号')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP01.SubjectInformation', verbose_name='课程号')),
            ],
        ),
        migrations.AddField(
            model_name='studentinformation',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP01.TeacherInformation', verbose_name='指导教师编号'),
        ),
        migrations.CreateModel(
            name='MajorSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP01.MajorInformation', verbose_name='专业号')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP01.SubjectInformation', verbose_name='课程号')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeInformation',
            fields=[
                ('employee_id', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='员工号')),
                ('ename', models.CharField(max_length=32, verbose_name='员工姓名')),
                ('esex', models.IntegerField(verbose_name='员工性别')),
                ('eage', models.IntegerField(verbose_name='员工年龄')),
                ('esalaries', models.IntegerField(verbose_name='薪水')),
                ('eentry_time', models.DateField(verbose_name='入职时间')),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP01.DepartmentInformation', verbose_name='所属部门号')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP01.SubjectInformation', verbose_name='本学期所授课程号')),
            ],
        ),
        migrations.AddField(
            model_name='departmentinformation',
            name='principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP01.EmployeeInformation', verbose_name='负责人'),
        ),
    ]
